// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnKYpRKovBV2JpU3eXbjWJYuTaqGuvnxI',
    appId: '1:907384913894:web:e39f957e118e193ad36027',
    messagingSenderId: '907384913894',
    projectId: 'auralynn-30af4',
    authDomain: 'auralynn-30af4.firebaseapp.com',
    storageBucket: 'auralynn-30af4.firebasestorage.app',
    measurementId: 'G-PZCWWW1Y71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU8kN2Coa1NEjGZo_XPHrjd99IRG2ZgfE',
    appId: '1:907384913894:android:bece0f4609cf11fdd36027',
    messagingSenderId: '907384913894',
    projectId: 'auralynn-30af4',
    storageBucket: 'auralynn-30af4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo0Ra22f2Je32WZA8XLW5PUi8y-Y9T8wY',
    appId: '1:907384913894:ios:5cc2c6d5655c2adbd36027',
    messagingSenderId: '907384913894',
    projectId: 'auralynn-30af4',
    storageBucket: 'auralynn-30af4.firebasestorage.app',
    iosBundleId: 'com.example.auralynn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo0Ra22f2Je32WZA8XLW5PUi8y-Y9T8wY',
    appId: '1:907384913894:ios:5cc2c6d5655c2adbd36027',
    messagingSenderId: '907384913894',
    projectId: 'auralynn-30af4',
    storageBucket: 'auralynn-30af4.firebasestorage.app',
    iosBundleId: 'com.example.auralynn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnKYpRKovBV2JpU3eXbjWJYuTaqGuvnxI',
    appId: '1:907384913894:web:34aa6f88243f6e11d36027',
    messagingSenderId: '907384913894',
    projectId: 'auralynn-30af4',
    authDomain: 'auralynn-30af4.firebaseapp.com',
    storageBucket: 'auralynn-30af4.firebasestorage.app',
    measurementId: 'G-LDZ489RN72',
  );

}