import 'package:flutter/material.dart';

final List<Map<String, dynamic>> allAchievements = [
  // Breathing Achievements
  {
    "id": "first_breath",
    "title": "First Breath",
    "description": "Complete your first breathing session",
    "feature": "Breathing",
    "imageUrl": "assets/images/achievements/first_breath.png",
    "isEarned": false,
    "difficulty": 1,
    "progress": null,
  },
  {
    "id": "consistent_breather_5",
    "title": "Consistent Breather (5)",
    "description": "Complete 5 breathing sessions",
    "feature": "Breathing",
    "imageUrl": "assets/images/achievements/consistent_breather.png",
    "isEarned": false,
    "difficulty": 2,
    "progress": {"current": 0, "total": 5},
  },
  {
    "id": "consistent_breather_25",
    "title": "Consistent Breather (25)",
    "description": "Complete 25 breathing sessions",
    "feature": "Breathing",
    "imageUrl": "assets/images/achievements/pro_breather.png",
    "isEarned": false,
    "difficulty": 4,
    "progress": {"current": 0, "total": 25},
  },

  // Mood Achievements
  {
    "id": "first_check_in",
    "title": "First Check-in",
    "description": "Log your first mood entry",
    "feature": "Mood",
    "imageUrl": "assets/images/achievements/first_check_in.png",
    "isEarned": false,
    "difficulty": 1,
    "progress": null,
  },
  {
    "id": "mood_mapper_7",
    "title": "Mood Mapper (7 Days)",
    "description": "Log your mood for 7 consecutive days",
    "feature": "Mood",
    "imageUrl": "assets/images/achievements/mood_mapper.png",
    "isEarned": false,
    "difficulty": 3,
    "progress": {"current": 0, "total": 7},
  },
  {
    "id": "emotion_explorer",
    "title": "Emotion Explorer",
    "description": "Log at least 5 different mood types",
    "feature": "Mood",
    "imageUrl": "assets/images/achievements/emotion_explorer.png",
    "isEarned": false,
    "difficulty": 2,
    "progress": null,
  },

  // Focus Achievements
  {
    "id": "first_focus",
    "title": "First Focus",
    "description": "Complete your first focus session",
    "feature": "Focus",
    "imageUrl": "assets/images/achievements/first_focus.png",
    "isEarned": false,
    "difficulty": 1,
    "progress": null,
  },
  {
    "id": "focused_streak_5",
    "title": "Focused Streak (5)",
    "description": "Complete 5 focus sessions",
    "feature": "Focus",
    "imageUrl": "assets/images/achievements/focused_streak.png",
    "isEarned": false,
    "difficulty": 3,
    "progress": {"current": 0, "total": 5},
  },
  {
    "id": "concentration_master_30min",
    "title": "Concentration Master (30min)",
    "description": "Complete a 30-minute focus session",
    "feature": "Focus",
    "imageUrl": "assets/images/achievements/concentration_master.png",
    "isEarned": false,
    "difficulty": 4,
    "progress": null,
  },
];
